config/routes.rb
Rails.application.routes.draw do
  resources :series
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
	has_many :menifests
	has_many :series, :through => :menifests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menifest.rb
class Menifest < ApplicationRecord
  belongs_to :actor
  belongs_to :series
  belongs_to :shooting_location
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :series
	belongs_to :user
end

app/models/series.rb
class Series < ApplicationRecord
	has_many :menifests
	has_many :actors, :through => :menifests
	has_many :shooting_locations, :through => :menifests
	
	has_many :users, :through => :reviews

	has_many :reviews
end

app/models/shooting_location.rb
class ShootingLocation < ApplicationRecord
	has_many :menifests
	has_many :series, :through => :menifests
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews
	has_many :series, :through => :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    if params["actor"]
      actor = Actor.where("name like ?", "#{params["actor"]} %").first
      @series = actor.present? ? actor.series.includes(:reviews) : []
    else
      @series = Series.includes(:reviews).all
    end
  end

  # GET /series/1 or /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: "Series was successfully created." }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: "Series was successfully updated." }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: "Series was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:series).permit(:name, :genre, :no_of_seasons, :director, :date_of_first_release)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TVSeriesAndRating</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/series/_form.html.erb
<%= form_with(model: series, local: true) do |form| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% series.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :no_of_seasons %>
    <%= form.number_field :no_of_seasons %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="field">
    <%= form.label :date_of_first_release %>
    <%= form.date_select :date_of_first_release %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<% if @series.size > 0 %>
  <h1>Series</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Genre</th>
        <th>No of seasons</th>
        <th>Director</th>
        <th>Date of first release</th>
        <th>Actors</th>
        <th>Shoot Locations</th>
        <th>Average Rating</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @series.each do |series| %>
        <tr>
          <td><%= series.name %></td>
          <td><%= series.genre %></td>
          <td><%= series.no_of_seasons %></td>
          <td><%= series.director %></td>
          <td><%= series.date_of_first_release %></td>
          <td><%= series.actors.collect(&:name).uniq %></td>
          <td><%= series.shooting_locations.collect(&:city).uniq %></td>
          <% total_rating = 0 
              series.reviews.each{|rev| total_rating += rev.stars}
          %>
          <td><%= total_rating/(series.reviews.count).to_f %></td>
          <td><%= link_to 'Show', series %></td>
          <td><%= link_to 'Edit', edit_series_path(series) %></td>
          <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div> <b>No Series with requested filter Present in Syestem, Please try creating a new one from below link </b>b></div>
<% end %>
<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @series.name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @series.genre %>
</p>

<p>
  <strong>No of seasons:</strong>
  <%= @series.no_of_seasons %>
</p>

<p>
  <strong>Director:</strong>
  <%= @series.director %>
</p>

<p>
  <strong>Date of first release:</strong>
  <%= @series.date_of_first_release %>
</p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>